[package]
name = "custom_mutator"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0.216", features = ["derive"] }
serde_json = "1.0.133"
indexmap = { version = "2.7.0", features = ["serde"] }
log4rs = "1.3.0"
log = "0.4.22"