[package]
name = "swap_check"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0.216", features = ["derive"] }
serde_json = "1.0.133"
indexmap = { version = "2.7.0", features = ["serde"] }