[package]
name = "rfc_processor"
version = "0.1.0"
edition = "2021"

[dependencies]
regex = "1.5"
reqwest = { version = "0.11", features = ["blocking"] }
lazy_static = "1.4"
colored = "2.0"

[dev-dependencies]
mockall = "0.13"
tempfile = "3.10"