[package]
name = "file_manage"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.11", features = ["blocking"] }
regex = "1.5"
lazy_static = "1.4.0"
tokio = { version = "1.0", features = ["full"] }
