[package]
name = "openai_key_call"
version = "0.1.0"
edition = "2021"

[dependencies]
openai-api-rs = "5.0.4"
toml = "0.8"
colored = "2.0"
serde_json = "1.0"
tokio = { version = "1.39", features = ["full"] }